sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  slack:
    secure: Dy+hqSo/EDsryq0lt2Pqpr6sivgfmmPxIQJYTc8t/JdhIOx/AkAGZpQw54szruJqsi1vJT5SSwxqIeFAE7B3p4FAH+C2aBUa+HnW9NY30mHiToBTFTAbb7SFOFatCHuJHVDO++IVJ9SjZKx1h3+/rwBT7Pky4CfP2rh1zDDTPg4=
  email:
    recipients:
      secure: DbLsY7BwQ0sCQ2/7iwOFAUFmjUqPl4sBP6kJ0El+DwRMn9mPP9JnZi2myQOHQhcSkR/ySYnncK4cJtANnJEnoeypTOb6R+gqU25cr4MpokMqvkajTmsDDOO5ax6Ogb3Yyy1dN4DJS2FSIfKC+MH3rimbyIGa4zfuMtjMrz6ZG9Q=
